<?php

/**
 * @file
 * Contains drupal_planet.module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function drupal_planet_theme($existing, $type, $theme, $path) {
  return [
    // Let the drupal planet view to use the custom template.
    'views_view_rss__drupal_planet' => [
      'template' => 'views-view-rss--drupal-planet',
      'base hook' => 'views_view_rss',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function drupal_planet_preprocess_views_view_rss(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  if ($view->current_display === 'feed_1' && $view->id() === 'drupal_planet') {
    // Provide a new variable for the custom template.
    $display = $view->getDisplay();

    $variables['feed_url'] = $display->getUrl()->setAbsolute()->toString();
    // Alter namespaces.
    $style = $view->getStyle();
    $style->namespaces = array_filter( $style->namespaces, function ($key) {
      return $key === 'xmlns:dc';
    }, ARRAY_FILTER_USE_KEY);
    $style->namespaces['xmlns:atom'] = 'http://www.w3.org/2005/Atom';
    $variables['namespaces'] = new Attribute($style->namespaces);
  }
}
